version: "3.2"
services:
  backend:
    container_name: "space_ocean_backend"
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8000:8000
    depends_on:
      - db
    volumes:
      - .:/code
    environment:
      DEBUG: "true"
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"

  db:
    container_name: "space_ocean_db"
    image: postgres:12.1-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB

volumes:
  dbdata: